### to create new user RUN: docker-compose run --rm dspace-cli create-administrator -e test@test.edu -f admin -l user -p admin -c en
---
version: "3.8"

services:
  dspace-cli:
    image: "dspace/dspace-cli:${DSPACE_VERSION}"
    container_name: dspace-cli
    environment:
      - dspace__P__dir=/dspace
      - db__P__url=jdbc:postgresql://dspacedb:5432/dspace
      - solr__P__server=http://dspacesolr:8983/solr
    volumes:
      - type: bind
        source: ${DATA_FOLDER}/assetstore
        target: /dspace/assetstore
    entrypoint: /dspace/bin/dspace
    command: help
    networks:
      - dspacenet
    tty: true
    stdin_open: true

networks:
  dspacenet:
    external: true
    name: dspacenet

