services:
  dspace-angular:
    image: "${DOCKER_REGISTRY:-dspace}/dspace-angular:${DSPACE_VERSION:-latest}"
    container_name: dspace-angular
    environment:
      - DSPACE_UI_SSL=false
      - DSPACE_UI_HOST=${DSPACE_HOSTNAME:-localhost}
      - DSPACE_UI_PORT=4000
      - DSPACE_UI_NAMESPACE=/
      - DSPACE_REST_SSL=false
      - DSPACE_REST_HOST=${DSPACE_HOSTNAME:-localhost}
      - DSPACE_REST_PORT=8080
      - DSPACE_REST_NAMESPACE=/server
    volumes:
      - type: bind
        source: "${DATA_FOLDER}/angular"
        target: /app/config
    networks:
      - dspacenet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dspace-angular.rule=Host(`${DSPACE_HOSTNAME}`)"
      - "traefik.http.services.dspace-angular.loadbalancer.server.port=4000"

networks:
  dspacenet:
    external: true
    name: dspacenet
